{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "service-name-from-ingress.serviceAccountName" . }}
  labels:
    {{- include "service-name-from-ingress.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "service-name-from-ingress.serviceAccountName" . }}    
  labels:
    {{- include "service-name-from-ingress.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  - extensions
  - networking.k8s.io
  resources:
  - services
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  - extensions
  - networking.k8s.io
  resourceNames:
  - {{ .Values.alb.serviceName | default ( include "service-name-from-ingress.fullname" . ) }}
  resources:
  - services
  verbs:
  - update
  - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "service-name-from-ingress.serviceAccountName" . }}  
  labels:
    {{- include "service-name-from-ingress.labels" . | nindent 4 }}

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "service-name-from-ingress.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "service-name-from-ingress.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
